[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_contracts = "3D7d2dRwysPv1ov5BzT934W2NYS9o7gfjBP2EphgVNXX"

[programs.devnet]
solana_contracts = "3D7d2dRwysPv1ov5BzT934W2NYS9o7gfjBP2EphgVNXX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/deployer-devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.ts\""
